1 Vectores y matrices

```{r}
# 1.1 Cree un vector por cada estudiante que almacene los 5 registros
student_1 <-c(50.4,62.3,92.1,77.6,TRUE)
student_2 <-c(41.7,87.9,75.3,72.4,FALSE)
student_3 <-c(30.3,67.8,69.3,71.2,FALSE)
student_4 <-c(65.4,85.1,92.3,96.8,TRUE)
student_5 <-c(70.4,88.2,95.2,90.7,TRUE)

#1.2 Cree el vector students_vector, sus elementos serán cada uno de los vectores creados anteriormente:
students_vector<-c(student_1, student_2, student_3, student_4, student_5)

#1.3Construya una matriz de nombre students_matrix que reciba como parámetro students_vector
students_matrix<-matrix(students_vector, nrow=5, ncol=5, byrow=TRUE)


#2 Nombrado de una matriz
#2.1Cree los vectores name_students y name_courses_legal_age con los siguientes valores
name_students<-c("Lily Brown", "Davis Moore","Susan Taylor", "Mike Jones", "Tom Hill")
name_courses_legal_age<-c("TIC", "Accounting", "Psychology", "Ethics", "Legal_age")
#2.2Utilice estos vectores para crear el nombrado de filas y columnas de la matriz students_vector. En las filas deben aparecer los estudiantes y en columnas los cursos y si es mayor de edad.
colnames(students_matrix) <- name_courses_legal_age
rownames(students_matrix) <- name_students

#3rowSums,cbind
#3.1 Cree el vector total_grade_student que contenga la sumatoria de todas las notas por cada estudiante, utilice la función rowSum para hacerlo, tome en cuenta que solo debe considerar las primera 4 columnas, porque la última corresponde a la mayoría de edad.

total_grade_student <- rowSums(students_matrix[, 1:4])
#3.2 Pegue el vector total_grade_student con la matriz students_matrix por medio de la función cbind y asigne el resultado a una nueva matriz de nombre result_students

result_students <- cbind(students_matrix, total_grade_student)
#4 Seleccionando elementos de una matriz 
#De la matriz result_students seleccione la fila 1, 3 y 5 y las columnas 2 y 4. Almacene el resultado en una variable de nombre selected_elements e imprima el resultado.

selected_elements <- result_students[c(1, 3, 5), c(2, 4)]
selected_elements
#5 Data frames
#5.1 Construya un data frame de nombre students_grades_df utilizando la matriz result_students como parámetro

students_grades_df <- as.data.frame(result_students)

students_grades_df

#5.2 Utilice la función subset en students_grades_df para filtrar por la siguiente condición: Que la columna Accounting sea mayor a 80 y que Legal_age sea verdadero.
subset(students_grades_df, Accounting > 80 & Legal_age == TRUE)

#6 Funciones, condiciones y blucles 
#6.1Construya una función de nombre students_projection que recorra la matriz result_students.
#6.2 Al recorrer filas y columnas obtendrá el valor de la nota que se encuentra en cada celda de la matriz, con este valor aplique las siguientes condiciones para imprimir un mensaje:
#6.2.1. Si la nota es menor o igual a 45 imprima "Student at risk"
#6.2.2. Si la nota es mayor a 45 y menor a 61 imprima “Student may be approved”
#6.2.3. Si la nota es mayor o igual a 61 imprima “Student approved”
students_projection <- function(x){
  n<-nrow(x)
  m<-ncol(x)-1
  for(i in 1:n){
    
    for(j in 1:m){
      nota<- x[i,j]
      if(j !=m){
        if (nota <=45){
          print("Student at risk")
        }else if (nota > 45 & nota < 61) {
          print("Student may be approved")
        } else {
          print("Student approved")
        }
      }
    }
  }
  
}

#students_projection(result_students)


#7 Data frames y lapply 
#7.1Construya la función index_education que reciba un parámetro de nombre grade
index_education<-function(grade){
  index <- (1+(grade/100))/2
  return(index)
}
#7.2. Utilice students_grades_df seleccionando todas las filas y solamente las primeras 4 columnas, luego asigne el resultado en all_students_grade.
all_students_grade <- subset(students_grades_df, select = 1:4)
all_students_grade
# Utilice lapply pasando de parámetros all_students_grade y la función index_education.
test_lapply <- lapply(all_students_grade,index_education)
test_lapply 
